name: Actualizar Datos Aire CDMX

on:
  schedule:
    # CRON: Se ejecuta cada 10 minutos exactos (00, 10, 20, 30, 40, 50)
    - cron: '*/10 * * * *'
  workflow_dispatch:      # Botón manual por si quieres probar

jobs:
  import-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      # 1. EL FIX DE SEGURIDAD (Obligatorio para que no te bloquee el gobierno)
      - name: Crear Configuración SSL Permisiva
        run: |
          cat <<EOF > openssl_unsafe.cnf
          openssl_conf = openssl_init
          [openssl_init]
          ssl_conf = ssl_sect
          [ssl_sect]
          system_default = system_default_sect
          [system_default_sect]
          CipherString = DEFAULT@SECLEVEL=1
          EOF
          echo "OPENSSL_CONF=$PWD/openssl_unsafe.cnf" >> $GITHUB_ENV

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true # CLAVE: Descarga binarios pre-compilados (Rapidísimo)

      # 2. CACHÉ AUTOMÁTICO
      # Esta acción detecta qué librerías necesitas, las instala y las guarda en caché.
      # La primera vez tardará un poco, ¡pero la segunda volará!
      - name: Instalar librerías con Caché
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::httr
            any::stringr
            any::dplyr
            any::readr

      - name: Correr script de scraping
        run: Rscript script.R

      - name: Guardar cambios
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add datos_aire.csv
          git commit -m "Actualización automática" || echo "Sin cambios"
          git push
