name: Actualizar Datos Aire CDMX

on:
  schedule:
    - cron: '*/5 * * * *'  # Se ejecuta cada hora (minuto 0)
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón para probar

jobs:
  import-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Instalar librerías
        run: |
          install.packages(c("httr", "stringr", "dplyr", "readr"))
        shell: Rscript {0}

      - name: Ver archivos (Debug)
        run: ls -R

      - name: Correr script de scraping
        run: Rscript script.R

      - name: Guardar cambios (Commit & Push)
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"
          git add datos_aire.csv
          git commit -m "Actualización automática de datos aire" || echo "Sin cambios para commitear"
          git push
